version: "3"
services:
  mongo1:
    image: mongo:5.0.9-focal
    command: mongod --replSet ycsbSet
    hostname: mongo1
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data-1:/data/db"
      - "mongo-config-1:/data/configdb"
    networks:
      - mongo-cluster
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tier == 1
  mongo2:
    image: mongo:5.0.9-focal
    command: mongod --replSet ycsbSet
    hostname: mongo2
    volumes:
      - "mongo-data-2:/data/db"
      - "mongo-config-2:/data/configdb"
    networks:
      - mongo-cluster
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tier == 2

  mongo3:
    image: mongo:5.0.9-focal
    command: mongod --replSet ycsbSet
    hostname: mongo3
    volumes:
      - "mongo-data-3:/data/db"
      - "mongo-config-3:/data/configdb"
    networks:
      - mongo-cluster
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tier == 1

networks:
  mongo-cluster:

volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  mongo-config-1:
  mongo-config-2:
  mongo-config-3:
