version: "3"
services:
  iperf:
    image: networkstatic/iperf3:latest
    command: iperf3 -s
    ports:
      - "5201:5201"
    networks:
      - iperf3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.dell == 1

networks:
  iperf3:
    driver_opts:
      com.docker.network.driver.mtu: 1500

